SyntaxError: Missing parentheses on Sqliv install
ile "/home/iamalive/Downloads/sqlivulscan/setup.py", line 25
    print "SQLiv (2.0) by {}".format(__author__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?